#!/bin/python3

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1700, 1000)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.picture = QtWidgets.QLabel(parent=Dialog)
        self.picture.setGeometry(QtCore.QRect(525, 20, 650, 960))
        self.picture.setText("")
        self.picture.setScaledContents(True)
        self.picture.setObjectName("picture")
        self.BR_speed_pic = QtWidgets.QLabel(parent=Dialog)
        self.BR_speed_pic.setGeometry(QtCore.QRect(1180, 750, 40, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BR_speed_pic.sizePolicy().hasHeightForWidth())
        self.BR_speed_pic.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BR_speed_pic.setFont(font)
        self.BR_speed_pic.setText("")
        self.BR_speed_pic.setScaledContents(True)
        self.BR_speed_pic.setObjectName("BR_speed_pic")
        self.BR_speed_label = QtWidgets.QLabel(parent=Dialog)
        self.BR_speed_label.setGeometry(QtCore.QRect(1240, 750, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BR_speed_label.setFont(font)
        self.BR_speed_label.setObjectName("BR_speed_label")
        self.FL_speed_pic = QtWidgets.QLabel(parent=Dialog)
        self.FL_speed_pic.setGeometry(QtCore.QRect(480, 60, 40, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FL_speed_pic.sizePolicy().hasHeightForWidth())
        self.FL_speed_pic.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FL_speed_pic.setFont(font)
        self.FL_speed_pic.setText("")
        self.FL_speed_pic.setScaledContents(True)
        self.FL_speed_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_speed_pic.setObjectName("FL_speed_pic")
        self.FL_speed_label = QtWidgets.QLabel(parent=Dialog)
        self.FL_speed_label.setGeometry(QtCore.QRect(390, 60, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FL_speed_label.setFont(font)
        self.FL_speed_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_speed_label.setObjectName("FL_speed_label")
        self.BL_speed_pic = QtWidgets.QLabel(parent=Dialog)
        self.BL_speed_pic.setGeometry(QtCore.QRect(480, 750, 40, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BL_speed_pic.sizePolicy().hasHeightForWidth())
        self.BL_speed_pic.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL_speed_pic.setFont(font)
        self.BL_speed_pic.setText("")
        self.BL_speed_pic.setScaledContents(True)
        self.BL_speed_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_speed_pic.setObjectName("BL_speed_pic")
        self.BL_speed_label = QtWidgets.QLabel(parent=Dialog)
        self.BL_speed_label.setGeometry(QtCore.QRect(390, 750, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BL_speed_label.setFont(font)
        self.BL_speed_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_speed_label.setObjectName("BL_speed_label")
        self.BR_break_label = QtWidgets.QLabel(parent=Dialog)
        self.BR_break_label.setGeometry(QtCore.QRect(1240, 830, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BR_break_label.setFont(font)
        self.BR_break_label.setObjectName("BR_break_label")
        self.BR_break_pic = QtWidgets.QLabel(parent=Dialog)
        self.BR_break_pic.setGeometry(QtCore.QRect(1180, 830, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BR_break_pic.setFont(font)
        self.BR_break_pic.setText("")
        self.BR_break_pic.setScaledContents(True)
        self.BR_break_pic.setObjectName("BR_break_pic")
        self.BR_steering_pic = QtWidgets.QLabel(parent=Dialog)
        self.BR_steering_pic.setGeometry(QtCore.QRect(1180, 790, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BR_steering_pic.setFont(font)
        self.BR_steering_pic.setText("")
        self.BR_steering_pic.setScaledContents(True)
        self.BR_steering_pic.setObjectName("BR_steering_pic")
        self.BR_steering_label = QtWidgets.QLabel(parent=Dialog)
        self.BR_steering_label.setGeometry(QtCore.QRect(1240, 790, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BR_steering_label.setFont(font)
        self.BR_steering_label.setObjectName("BR_steering_label")
        self.BL_break_label = QtWidgets.QLabel(parent=Dialog)
        self.BL_break_label.setGeometry(QtCore.QRect(410, 830, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BL_break_label.setFont(font)
        self.BL_break_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_break_label.setObjectName("BL_break_label")
        self.BL_break_pic = QtWidgets.QLabel(parent=Dialog)
        self.BL_break_pic.setGeometry(QtCore.QRect(480, 830, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL_break_pic.setFont(font)
        self.BL_break_pic.setText("")
        self.BL_break_pic.setScaledContents(True)
        self.BL_break_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_break_pic.setObjectName("BL_break_pic")
        self.BL_steering_pic = QtWidgets.QLabel(parent=Dialog)
        self.BL_steering_pic.setGeometry(QtCore.QRect(480, 790, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL_steering_pic.setFont(font)
        self.BL_steering_pic.setText("")
        self.BL_steering_pic.setScaledContents(True)
        self.BL_steering_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_steering_pic.setObjectName("BL_steering_pic")
        self.BL_steering_label = QtWidgets.QLabel(parent=Dialog)
        self.BL_steering_label.setGeometry(QtCore.QRect(410, 790, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BL_steering_label.setFont(font)
        self.BL_steering_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_steering_label.setObjectName("BL_steering_label")
        self.FL_break_label = QtWidgets.QLabel(parent=Dialog)
        self.FL_break_label.setGeometry(QtCore.QRect(410, 140, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FL_break_label.setFont(font)
        self.FL_break_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_break_label.setObjectName("FL_break_label")
        self.FL_break_pic = QtWidgets.QLabel(parent=Dialog)
        self.FL_break_pic.setGeometry(QtCore.QRect(480, 140, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FL_break_pic.setFont(font)
        self.FL_break_pic.setText("")
        self.FL_break_pic.setScaledContents(True)
        self.FL_break_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_break_pic.setObjectName("FL_break_pic")
        self.FL_steering_pic = QtWidgets.QLabel(parent=Dialog)
        self.FL_steering_pic.setGeometry(QtCore.QRect(480, 100, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FL_steering_pic.setFont(font)
        self.FL_steering_pic.setText("")
        self.FL_steering_pic.setScaledContents(True)
        self.FL_steering_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_steering_pic.setObjectName("FL_steering_pic")
        self.FL_steering_label = QtWidgets.QLabel(parent=Dialog)
        self.FL_steering_label.setGeometry(QtCore.QRect(410, 100, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FL_steering_label.setFont(font)
        self.FL_steering_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_steering_label.setObjectName("FL_steering_label")
        self.FR_break_pic = QtWidgets.QLabel(parent=Dialog)
        self.FR_break_pic.setGeometry(QtCore.QRect(1180, 140, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FR_break_pic.setFont(font)
        self.FR_break_pic.setText("")
        self.FR_break_pic.setScaledContents(True)
        self.FR_break_pic.setObjectName("FR_break_pic")
        self.FR_steering_pic = QtWidgets.QLabel(parent=Dialog)
        self.FR_steering_pic.setGeometry(QtCore.QRect(1180, 100, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FR_steering_pic.setFont(font)
        self.FR_steering_pic.setText("")
        self.FR_steering_pic.setScaledContents(True)
        self.FR_steering_pic.setObjectName("FR_steering_pic")
        self.FR_speed_pic = QtWidgets.QLabel(parent=Dialog)
        self.FR_speed_pic.setGeometry(QtCore.QRect(1180, 60, 40, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FR_speed_pic.sizePolicy().hasHeightForWidth())
        self.FR_speed_pic.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FR_speed_pic.setFont(font)
        self.FR_speed_pic.setText("")
        self.FR_speed_pic.setScaledContents(True)
        self.FR_speed_pic.setObjectName("FR_speed_pic")
        self.FR_steering_label = QtWidgets.QLabel(parent=Dialog)
        self.FR_steering_label.setGeometry(QtCore.QRect(1240, 100, 50, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FR_steering_label.setFont(font)
        self.FR_steering_label.setObjectName("FR_steering_label")
        self.Fr_break_label = QtWidgets.QLabel(parent=Dialog)
        self.Fr_break_label.setGeometry(QtCore.QRect(1240, 140, 50, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Fr_break_label.setFont(font)
        self.Fr_break_label.setObjectName("Fr_break_label")
        self.FR_speed_label = QtWidgets.QLabel(parent=Dialog)
        self.FR_speed_label.setGeometry(QtCore.QRect(1240, 60, 80, 21))
        self.FR_speed_label.setBaseSize(QtCore.QSize(6, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FR_speed_label.setFont(font)
        self.FR_speed_label.setObjectName("FR_speed_label")
        self.FR_break_error_label = QtWidgets.QLabel(parent=Dialog)
        self.FR_break_error_label.setGeometry(QtCore.QRect(1240, 220, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FR_break_error_label.setFont(font)
        self.FR_break_error_label.setObjectName("FR_break_error_label")
        self.FR_break_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.FR_break_error_pic.setGeometry(QtCore.QRect(1180, 220, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FR_break_error_pic.setFont(font)
        self.FR_break_error_pic.setText("")
        self.FR_break_error_pic.setScaledContents(True)
        self.FR_break_error_pic.setObjectName("FR_break_error_pic")
        self.FR_steering_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.FR_steering_error_pic.setGeometry(QtCore.QRect(1180, 180, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FR_steering_error_pic.setFont(font)
        self.FR_steering_error_pic.setText("")
        self.FR_steering_error_pic.setScaledContents(True)
        self.FR_steering_error_pic.setObjectName("FR_steering_error_pic")
        self.FR_steering_error_label = QtWidgets.QLabel(parent=Dialog)
        self.FR_steering_error_label.setGeometry(QtCore.QRect(1240, 180, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FR_steering_error_label.setFont(font)
        self.FR_steering_error_label.setObjectName("FR_steering_error_label")
        self.FL_steering_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.FL_steering_error_pic.setGeometry(QtCore.QRect(480, 180, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FL_steering_error_pic.setFont(font)
        self.FL_steering_error_pic.setText("")
        self.FL_steering_error_pic.setScaledContents(True)
        self.FL_steering_error_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_steering_error_pic.setObjectName("FL_steering_error_pic")
        self.FL_steering_error_label = QtWidgets.QLabel(parent=Dialog)
        self.FL_steering_error_label.setGeometry(QtCore.QRect(410, 180, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FL_steering_error_label.setFont(font)
        self.FL_steering_error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_steering_error_label.setObjectName("FL_steering_error_label")
        self.FL_break_error_label = QtWidgets.QLabel(parent=Dialog)
        self.FL_break_error_label.setGeometry(QtCore.QRect(410, 220, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FL_break_error_label.setFont(font)
        self.FL_break_error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_break_error_label.setObjectName("FL_break_error_label")
        self.FL_break_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.FL_break_error_pic.setGeometry(QtCore.QRect(480, 220, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FL_break_error_pic.setFont(font)
        self.FL_break_error_pic.setText("")
        self.FL_break_error_pic.setScaledContents(True)
        self.FL_break_error_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_break_error_pic.setObjectName("FL_break_error_pic")
        self.BR_steering_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.BR_steering_error_pic.setGeometry(QtCore.QRect(1180, 870, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BR_steering_error_pic.setFont(font)
        self.BR_steering_error_pic.setText("")
        self.BR_steering_error_pic.setScaledContents(True)
        self.BR_steering_error_pic.setObjectName("BR_steering_error_pic")
        self.BR_steering_error_label = QtWidgets.QLabel(parent=Dialog)
        self.BR_steering_error_label.setGeometry(QtCore.QRect(1240, 870, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BR_steering_error_label.setFont(font)
        self.BR_steering_error_label.setObjectName("BR_steering_error_label")
        self.BR_break_error_label = QtWidgets.QLabel(parent=Dialog)
        self.BR_break_error_label.setGeometry(QtCore.QRect(1240, 910, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BR_break_error_label.setFont(font)
        self.BR_break_error_label.setObjectName("BR_break_error_label")
        self.BR_break_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.BR_break_error_pic.setGeometry(QtCore.QRect(1180, 910, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BR_break_error_pic.setFont(font)
        self.BR_break_error_pic.setText("")
        self.BR_break_error_pic.setScaledContents(True)
        self.BR_break_error_pic.setObjectName("BR_break_error_pic")
        self.BL_steering_error_label = QtWidgets.QLabel(parent=Dialog)
        self.BL_steering_error_label.setGeometry(QtCore.QRect(410, 870, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BL_steering_error_label.setFont(font)
        self.BL_steering_error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_steering_error_label.setObjectName("BL_steering_error_label")
        self.BL_break_error_label = QtWidgets.QLabel(parent=Dialog)
        self.BL_break_error_label.setGeometry(QtCore.QRect(410, 910, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BL_break_error_label.setFont(font)
        self.BL_break_error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_break_error_label.setObjectName("BL_break_error_label")
        self.BL_steering_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.BL_steering_error_pic.setGeometry(QtCore.QRect(480, 870, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL_steering_error_pic.setFont(font)
        self.BL_steering_error_pic.setText("")
        self.BL_steering_error_pic.setScaledContents(True)
        self.BL_steering_error_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_steering_error_pic.setObjectName("BL_steering_error_pic")
        self.BL_break_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.BL_break_error_pic.setGeometry(QtCore.QRect(480, 910, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL_break_error_pic.setFont(font)
        self.BL_break_error_pic.setText("")
        self.BL_break_error_pic.setScaledContents(True)
        self.BL_break_error_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_break_error_pic.setObjectName("BL_break_error_pic")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.BR_speed_label.setText(_translate("Dialog", "BR"))
        self.FL_speed_label.setText(_translate("Dialog", "FL"))
        self.BL_speed_label.setText(_translate("Dialog", "BL"))
        self.BR_break_label.setText(_translate("Dialog", "BR"))
        self.BR_steering_label.setText(_translate("Dialog", "BR"))
        self.BL_break_label.setText(_translate("Dialog", "BL"))
        self.BL_steering_label.setText(_translate("Dialog", "BL"))
        self.FL_break_label.setText(_translate("Dialog", "FL"))
        self.FL_steering_label.setText(_translate("Dialog", "FL"))
        self.FR_steering_label.setText(_translate("Dialog", "FR"))
        self.Fr_break_label.setText(_translate("Dialog", "FR"))
        self.FR_speed_label.setText(_translate("Dialog", "FR"))
        self.FR_break_error_label.setText(_translate("Dialog", "FR"))
        self.FR_steering_error_label.setText(_translate("Dialog", "FR"))
        self.FL_steering_error_label.setText(_translate("Dialog", "FL"))
        self.FL_break_error_label.setText(_translate("Dialog", "FL"))
        self.BR_steering_error_label.setText(_translate("Dialog", "BR"))
        self.BR_break_error_label.setText(_translate("Dialog", "BR"))
        self.BL_steering_error_label.setText(_translate("Dialog", "BL"))
        self.BL_break_error_label.setText(_translate("Dialog", "BL"))

