#!/bin/python3


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1700, 1020)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.picture = QtWidgets.QLabel(parent=Dialog)
        self.picture.setGeometry(QtCore.QRect(525, 50, 650, 900))
        self.picture.setText("")
        self.picture.setScaledContents(True)
        self.picture.setObjectName("picture")
        self.BR_speed_pic = QtWidgets.QLabel(parent=Dialog)
        self.BR_speed_pic.setGeometry(QtCore.QRect(1180, 730, 40, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BR_speed_pic.sizePolicy().hasHeightForWidth())
        self.BR_speed_pic.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BR_speed_pic.setFont(font)
        self.BR_speed_pic.setText("")
        self.BR_speed_pic.setScaledContents(True)
        self.BR_speed_pic.setObjectName("BR_speed_pic")
        self.BR_speed_label = QtWidgets.QLabel(parent=Dialog)
        self.BR_speed_label.setGeometry(QtCore.QRect(1240, 730, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BR_speed_label.setFont(font)
        self.BR_speed_label.setObjectName("BR_speed_label")
        self.FL_speed_pic = QtWidgets.QLabel(parent=Dialog)
        self.FL_speed_pic.setGeometry(QtCore.QRect(480, 90, 40, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FL_speed_pic.sizePolicy().hasHeightForWidth())
        self.FL_speed_pic.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FL_speed_pic.setFont(font)
        self.FL_speed_pic.setText("")
        self.FL_speed_pic.setScaledContents(True)
        self.FL_speed_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_speed_pic.setObjectName("FL_speed_pic")
        self.FL_speed_label = QtWidgets.QLabel(parent=Dialog)
        self.FL_speed_label.setGeometry(QtCore.QRect(380, 90, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FL_speed_label.setFont(font)
        self.FL_speed_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_speed_label.setObjectName("FL_speed_label")
        self.BL_speed_pic = QtWidgets.QLabel(parent=Dialog)
        self.BL_speed_pic.setGeometry(QtCore.QRect(480, 730, 40, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BL_speed_pic.sizePolicy().hasHeightForWidth())
        self.BL_speed_pic.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL_speed_pic.setFont(font)
        self.BL_speed_pic.setText("")
        self.BL_speed_pic.setScaledContents(True)
        self.BL_speed_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_speed_pic.setObjectName("BL_speed_pic")
        self.BL_speed_label = QtWidgets.QLabel(parent=Dialog)
        self.BL_speed_label.setGeometry(QtCore.QRect(380, 730, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BL_speed_label.setFont(font)
        self.BL_speed_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_speed_label.setObjectName("BL_speed_label")
        self.BR_break_label = QtWidgets.QLabel(parent=Dialog)
        self.BR_break_label.setGeometry(QtCore.QRect(1240, 810, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BR_break_label.setFont(font)
        self.BR_break_label.setObjectName("BR_break_label")
        self.BR_break_pic = QtWidgets.QLabel(parent=Dialog)
        self.BR_break_pic.setGeometry(QtCore.QRect(1180, 810, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BR_break_pic.setFont(font)
        self.BR_break_pic.setText("")
        self.BR_break_pic.setScaledContents(True)
        self.BR_break_pic.setObjectName("BR_break_pic")
        self.BR_steering_pic = QtWidgets.QLabel(parent=Dialog)
        self.BR_steering_pic.setGeometry(QtCore.QRect(1180, 770, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BR_steering_pic.setFont(font)
        self.BR_steering_pic.setText("")
        self.BR_steering_pic.setScaledContents(True)
        self.BR_steering_pic.setObjectName("BR_steering_pic")
        self.BR_steering_label = QtWidgets.QLabel(parent=Dialog)
        self.BR_steering_label.setGeometry(QtCore.QRect(1240, 770, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BR_steering_label.setFont(font)
        self.BR_steering_label.setObjectName("BR_steering_label")
        self.BL_break_label = QtWidgets.QLabel(parent=Dialog)
        self.BL_break_label.setGeometry(QtCore.QRect(410, 810, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BL_break_label.setFont(font)
        self.BL_break_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_break_label.setObjectName("BL_break_label")
        self.BL_break_pic = QtWidgets.QLabel(parent=Dialog)
        self.BL_break_pic.setGeometry(QtCore.QRect(480, 810, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL_break_pic.setFont(font)
        self.BL_break_pic.setText("")
        self.BL_break_pic.setScaledContents(True)
        self.BL_break_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_break_pic.setObjectName("BL_break_pic")
        self.BL_steering_pic = QtWidgets.QLabel(parent=Dialog)
        self.BL_steering_pic.setGeometry(QtCore.QRect(480, 770, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL_steering_pic.setFont(font)
        self.BL_steering_pic.setText("")
        self.BL_steering_pic.setScaledContents(True)
        self.BL_steering_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_steering_pic.setObjectName("BL_steering_pic")
        self.BL_steering_label = QtWidgets.QLabel(parent=Dialog)
        self.BL_steering_label.setGeometry(QtCore.QRect(410, 770, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BL_steering_label.setFont(font)
        self.BL_steering_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_steering_label.setObjectName("BL_steering_label")
        self.FL_break_label = QtWidgets.QLabel(parent=Dialog)
        self.FL_break_label.setGeometry(QtCore.QRect(410, 170, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FL_break_label.setFont(font)
        self.FL_break_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_break_label.setObjectName("FL_break_label")
        self.FL_break_pic = QtWidgets.QLabel(parent=Dialog)
        self.FL_break_pic.setGeometry(QtCore.QRect(480, 170, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FL_break_pic.setFont(font)
        self.FL_break_pic.setText("")
        self.FL_break_pic.setScaledContents(True)
        self.FL_break_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_break_pic.setObjectName("FL_break_pic")
        self.FL_steering_pic = QtWidgets.QLabel(parent=Dialog)
        self.FL_steering_pic.setGeometry(QtCore.QRect(480, 130, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FL_steering_pic.setFont(font)
        self.FL_steering_pic.setText("")
        self.FL_steering_pic.setScaledContents(True)
        self.FL_steering_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_steering_pic.setObjectName("FL_steering_pic")
        self.FL_steering_label = QtWidgets.QLabel(parent=Dialog)
        self.FL_steering_label.setGeometry(QtCore.QRect(410, 130, 50, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FL_steering_label.setFont(font)
        self.FL_steering_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_steering_label.setObjectName("FL_steering_label")
        self.FR_break_pic = QtWidgets.QLabel(parent=Dialog)
        self.FR_break_pic.setGeometry(QtCore.QRect(1180, 170, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FR_break_pic.setFont(font)
        self.FR_break_pic.setText("")
        self.FR_break_pic.setScaledContents(True)
        self.FR_break_pic.setObjectName("FR_break_pic")
        self.FR_steering_pic = QtWidgets.QLabel(parent=Dialog)
        self.FR_steering_pic.setGeometry(QtCore.QRect(1180, 130, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FR_steering_pic.setFont(font)
        self.FR_steering_pic.setText("")
        self.FR_steering_pic.setScaledContents(True)
        self.FR_steering_pic.setObjectName("FR_steering_pic")
        self.FR_speed_pic = QtWidgets.QLabel(parent=Dialog)
        self.FR_speed_pic.setGeometry(QtCore.QRect(1180, 90, 40, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FR_speed_pic.sizePolicy().hasHeightForWidth())
        self.FR_speed_pic.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FR_speed_pic.setFont(font)
        self.FR_speed_pic.setText("")
        self.FR_speed_pic.setScaledContents(True)
        self.FR_speed_pic.setObjectName("FR_speed_pic")
        self.FR_steering_label = QtWidgets.QLabel(parent=Dialog)
        self.FR_steering_label.setGeometry(QtCore.QRect(1240, 130, 50, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FR_steering_label.setFont(font)
        self.FR_steering_label.setObjectName("FR_steering_label")
        self.Fr_break_label = QtWidgets.QLabel(parent=Dialog)
        self.Fr_break_label.setGeometry(QtCore.QRect(1240, 170, 50, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Fr_break_label.setFont(font)
        self.Fr_break_label.setObjectName("Fr_break_label")
        self.FR_speed_label = QtWidgets.QLabel(parent=Dialog)
        self.FR_speed_label.setGeometry(QtCore.QRect(1240, 90, 80, 21))
        self.FR_speed_label.setBaseSize(QtCore.QSize(6, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FR_speed_label.setFont(font)
        self.FR_speed_label.setObjectName("FR_speed_label")
        self.FR_break_error_label = QtWidgets.QLabel(parent=Dialog)
        self.FR_break_error_label.setGeometry(QtCore.QRect(1240, 250, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FR_break_error_label.setFont(font)
        self.FR_break_error_label.setObjectName("FR_break_error_label")
        self.FR_break_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.FR_break_error_pic.setGeometry(QtCore.QRect(1180, 250, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FR_break_error_pic.setFont(font)
        self.FR_break_error_pic.setText("")
        self.FR_break_error_pic.setScaledContents(True)
        self.FR_break_error_pic.setObjectName("FR_break_error_pic")
        self.FR_steering_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.FR_steering_error_pic.setGeometry(QtCore.QRect(1180, 210, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FR_steering_error_pic.setFont(font)
        self.FR_steering_error_pic.setText("")
        self.FR_steering_error_pic.setScaledContents(True)
        self.FR_steering_error_pic.setObjectName("FR_steering_error_pic")
        self.FR_steering_error_label = QtWidgets.QLabel(parent=Dialog)
        self.FR_steering_error_label.setGeometry(QtCore.QRect(1240, 210, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FR_steering_error_label.setFont(font)
        self.FR_steering_error_label.setObjectName("FR_steering_error_label")
        self.FL_steering_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.FL_steering_error_pic.setGeometry(QtCore.QRect(480, 210, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FL_steering_error_pic.setFont(font)
        self.FL_steering_error_pic.setText("")
        self.FL_steering_error_pic.setScaledContents(True)
        self.FL_steering_error_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_steering_error_pic.setObjectName("FL_steering_error_pic")
        self.FL_steering_error_label = QtWidgets.QLabel(parent=Dialog)
        self.FL_steering_error_label.setGeometry(QtCore.QRect(410, 210, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FL_steering_error_label.setFont(font)
        self.FL_steering_error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_steering_error_label.setObjectName("FL_steering_error_label")
        self.FL_break_error_label = QtWidgets.QLabel(parent=Dialog)
        self.FL_break_error_label.setGeometry(QtCore.QRect(410, 250, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.FL_break_error_label.setFont(font)
        self.FL_break_error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_break_error_label.setObjectName("FL_break_error_label")
        self.FL_break_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.FL_break_error_pic.setGeometry(QtCore.QRect(480, 250, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FL_break_error_pic.setFont(font)
        self.FL_break_error_pic.setText("")
        self.FL_break_error_pic.setScaledContents(True)
        self.FL_break_error_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.FL_break_error_pic.setObjectName("FL_break_error_pic")
        self.BR_steering_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.BR_steering_error_pic.setGeometry(QtCore.QRect(1180, 850, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BR_steering_error_pic.setFont(font)
        self.BR_steering_error_pic.setText("")
        self.BR_steering_error_pic.setScaledContents(True)
        self.BR_steering_error_pic.setObjectName("BR_steering_error_pic")
        self.BR_steering_error_label = QtWidgets.QLabel(parent=Dialog)
        self.BR_steering_error_label.setGeometry(QtCore.QRect(1240, 850, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BR_steering_error_label.setFont(font)
        self.BR_steering_error_label.setObjectName("BR_steering_error_label")
        self.BR_break_error_label = QtWidgets.QLabel(parent=Dialog)
        self.BR_break_error_label.setGeometry(QtCore.QRect(1240, 890, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BR_break_error_label.setFont(font)
        self.BR_break_error_label.setObjectName("BR_break_error_label")
        self.BR_break_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.BR_break_error_pic.setGeometry(QtCore.QRect(1180, 890, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BR_break_error_pic.setFont(font)
        self.BR_break_error_pic.setText("")
        self.BR_break_error_pic.setScaledContents(True)
        self.BR_break_error_pic.setObjectName("BR_break_error_pic")
        self.BL_steering_error_label = QtWidgets.QLabel(parent=Dialog)
        self.BL_steering_error_label.setGeometry(QtCore.QRect(410, 850, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BL_steering_error_label.setFont(font)
        self.BL_steering_error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_steering_error_label.setObjectName("BL_steering_error_label")
        self.BL_break_error_label = QtWidgets.QLabel(parent=Dialog)
        self.BL_break_error_label.setGeometry(QtCore.QRect(410, 890, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BL_break_error_label.setFont(font)
        self.BL_break_error_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_break_error_label.setObjectName("BL_break_error_label")
        self.BL_steering_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.BL_steering_error_pic.setGeometry(QtCore.QRect(480, 850, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL_steering_error_pic.setFont(font)
        self.BL_steering_error_pic.setText("")
        self.BL_steering_error_pic.setScaledContents(True)
        self.BL_steering_error_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_steering_error_pic.setObjectName("BL_steering_error_pic")
        self.BL_break_error_pic = QtWidgets.QLabel(parent=Dialog)
        self.BL_break_error_pic.setGeometry(QtCore.QRect(480, 890, 40, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BL_break_error_pic.setFont(font)
        self.BL_break_error_pic.setText("")
        self.BL_break_error_pic.setScaledContents(True)
        self.BL_break_error_pic.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.BL_break_error_pic.setObjectName("BL_break_error_pic")
        self.grey_color = QtWidgets.QLabel(parent=Dialog)
        self.grey_color.setGeometry(QtCore.QRect(747, 350, 220, 308))
        self.grey_color.setText("")
        self.grey_color.setScaledContents(True)
        self.grey_color.setObjectName("grey_color")
        self.FR_FOV = QtWidgets.QLabel(parent=Dialog)
        self.FR_FOV.setGeometry(QtCore.QRect(880, 0, 120, 165))
        self.FR_FOV.setText("")
        self.FR_FOV.setScaledContents(True)
        self.FR_FOV.setObjectName("FR_FOV")
        self.FL_FOV = QtWidgets.QLabel(parent=Dialog)
        self.FL_FOV.setGeometry(QtCore.QRect(710, 0, 120, 170))
        self.FL_FOV.setText("")
        self.FL_FOV.setScaledContents(True)
        self.FL_FOV.setObjectName("FL_FOV")
        self.FR_ultrasonic_label = QtWidgets.QLabel(parent=Dialog)
        self.FR_ultrasonic_label.setGeometry(QtCore.QRect(915, 30, 50, 21))
        self.FR_ultrasonic_label.setBaseSize(QtCore.QSize(6, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.FR_ultrasonic_label.setFont(font)
        self.FR_ultrasonic_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.FR_ultrasonic_label.setObjectName("FR_ultrasonic_label")
        self.FL_ultrasonic_label = QtWidgets.QLabel(parent=Dialog)
        self.FL_ultrasonic_label.setGeometry(QtCore.QRect(745, 35, 50, 21))
        self.FL_ultrasonic_label.setBaseSize(QtCore.QSize(6, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.FL_ultrasonic_label.setFont(font)
        self.FL_ultrasonic_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.FL_ultrasonic_label.setObjectName("FL_ultrasonic_label")
        self.R_ultrasonic_label = QtWidgets.QLabel(parent=Dialog)
        self.R_ultrasonic_label.setGeometry(QtCore.QRect(1160, 495, 50, 21))
        self.R_ultrasonic_label.setBaseSize(QtCore.QSize(6, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.R_ultrasonic_label.setFont(font)
        self.R_ultrasonic_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.R_ultrasonic_label.setObjectName("R_ultrasonic_label")
        self.L_ultrasonic_label = QtWidgets.QLabel(parent=Dialog)
        self.L_ultrasonic_label.setGeometry(QtCore.QRect(510, 495, 50, 21))
        self.L_ultrasonic_label.setBaseSize(QtCore.QSize(6, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.L_ultrasonic_label.setFont(font)
        self.L_ultrasonic_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.L_ultrasonic_label.setObjectName("L_ultrasonic_label")
        self.BR_ultrasonic_label = QtWidgets.QLabel(parent=Dialog)
        self.BR_ultrasonic_label.setGeometry(QtCore.QRect(915, 960, 50, 21))
        self.BR_ultrasonic_label.setBaseSize(QtCore.QSize(6, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.BR_ultrasonic_label.setFont(font)
        self.BR_ultrasonic_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BR_ultrasonic_label.setObjectName("BR_ultrasonic_label")
        self.BL_ultrasonic_label = QtWidgets.QLabel(parent=Dialog)
        self.BL_ultrasonic_label.setGeometry(QtCore.QRect(745, 960, 50, 21))
        self.BL_ultrasonic_label.setBaseSize(QtCore.QSize(6, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.BL_ultrasonic_label.setFont(font)
        self.BL_ultrasonic_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.BL_ultrasonic_label.setObjectName("BL_ultrasonic_label")
        self.control_speed_label = QtWidgets.QLabel(parent=Dialog)
        self.control_speed_label.setGeometry(QtCore.QRect(820, 400, 80, 30))
        self.control_speed_label.setBaseSize(QtCore.QSize(6, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.control_speed_label.setFont(font)
        self.control_speed_label.setObjectName("control_speed_label")
        self.control_speed_pic = QtWidgets.QLabel(parent=Dialog)
        self.control_speed_pic.setGeometry(QtCore.QRect(760, 400, 40, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_speed_pic.sizePolicy().hasHeightForWidth())
        self.control_speed_pic.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.control_speed_pic.setFont(font)
        self.control_speed_pic.setText("")
        self.control_speed_pic.setScaledContents(True)
        self.control_speed_pic.setObjectName("control_speed_pic")
        self.control_steering_label = QtWidgets.QLabel(parent=Dialog)
        self.control_steering_label.setGeometry(QtCore.QRect(820, 440, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.control_steering_label.setFont(font)
        self.control_steering_label.setObjectName("control_steering_label")
        self.control_gear_label = QtWidgets.QLabel(parent=Dialog)
        self.control_gear_label.setGeometry(QtCore.QRect(820, 360, 50, 35))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.control_gear_label.setFont(font)
        self.control_gear_label.setObjectName("control_gear_label")
        self.control_break_pic = QtWidgets.QLabel(parent=Dialog)
        self.control_break_pic.setGeometry(QtCore.QRect(760, 480, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.control_break_pic.setFont(font)
        self.control_break_pic.setText("")
        self.control_break_pic.setScaledContents(True)
        self.control_break_pic.setObjectName("control_break_pic")
        self.control_break_label = QtWidgets.QLabel(parent=Dialog)
        self.control_break_label.setGeometry(QtCore.QRect(820, 480, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.control_break_label.setFont(font)
        self.control_break_label.setObjectName("control_break_label")
        self.gear_pic = QtWidgets.QLabel(parent=Dialog)
        self.gear_pic.setGeometry(QtCore.QRect(760, 360, 45, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gear_pic.setFont(font)
        self.gear_pic.setText("")
        self.gear_pic.setScaledContents(True)
        self.gear_pic.setObjectName("gear_pic")
        self.control_steering_pic = QtWidgets.QLabel(parent=Dialog)
        self.control_steering_pic.setGeometry(QtCore.QRect(760, 440, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.control_steering_pic.setFont(font)
        self.control_steering_pic.setText("")
        self.control_steering_pic.setScaledContents(True)
        self.control_steering_pic.setObjectName("control_steering_pic")
        self.Reverse = QtWidgets.QRadioButton(parent=Dialog)
        self.Reverse.setGeometry(QtCore.QRect(920, 420, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Reverse.setFont(font)
        self.Reverse.setObjectName("Reverse")
        self.batter_percentage_label = QtWidgets.QLabel(parent=Dialog)
        self.batter_percentage_label.setGeometry(QtCore.QRect(790, 540, 50, 30))
        self.batter_percentage_label.setBaseSize(QtCore.QSize(6, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.batter_percentage_label.setFont(font)
        self.batter_percentage_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.batter_percentage_label.setObjectName("batter_percentage_label")
        self.battery_current_label = QtWidgets.QLabel(parent=Dialog)
        self.battery_current_label.setGeometry(QtCore.QRect(870, 590, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.battery_current_label.setFont(font)
        self.battery_current_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.battery_current_label.setObjectName("battery_current_label")
        self.battery_temp_label = QtWidgets.QLabel(parent=Dialog)
        self.battery_temp_label.setGeometry(QtCore.QRect(790, 590, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.battery_temp_label.setFont(font)
        self.battery_temp_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.battery_temp_label.setObjectName("battery_temp_label")
        self.battery_voltage_label = QtWidgets.QLabel(parent=Dialog)
        self.battery_voltage_label.setGeometry(QtCore.QRect(870, 540, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.battery_voltage_label.setFont(font)
        self.battery_voltage_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.battery_voltage_label.setObjectName("battery_voltage_label")
        self.Drive = QtWidgets.QRadioButton(parent=Dialog)
        self.Drive.setGeometry(QtCore.QRect(920, 460, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Drive.setFont(font)
        self.Drive.setObjectName("Drive")
        self.Park = QtWidgets.QRadioButton(parent=Dialog)
        self.Park.setGeometry(QtCore.QRect(920, 380, 40, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Park.setFont(font)
        self.Park.setObjectName("Park")
        self.L_FOV = QtWidgets.QLabel(parent=Dialog)
        self.L_FOV.setGeometry(QtCore.QRect(480, 445, 165, 120))
        self.L_FOV.setText("")
        self.L_FOV.setScaledContents(True)
        self.L_FOV.setObjectName("L_FOV")
        self.R_FOV = QtWidgets.QLabel(parent=Dialog)
        self.R_FOV.setGeometry(QtCore.QRect(1070, 445, 165, 120))
        self.R_FOV.setText("")
        self.R_FOV.setScaledContents(True)
        self.R_FOV.setObjectName("R_FOV")
        self.BR_FOV = QtWidgets.QLabel(parent=Dialog)
        self.BR_FOV.setGeometry(QtCore.QRect(880, 850, 120, 165))
        self.BR_FOV.setText("")
        self.BR_FOV.setScaledContents(True)
        self.BR_FOV.setObjectName("BR_FOV")
        self.BL_FOV = QtWidgets.QLabel(parent=Dialog)
        self.BL_FOV.setGeometry(QtCore.QRect(710, 850, 120, 165))
        self.BL_FOV.setText("")
        self.BL_FOV.setScaledContents(True)
        self.BL_FOV.setObjectName("BL_FOV")
        self.battery_pic = QtWidgets.QLabel(parent=Dialog)
        self.battery_pic.setGeometry(QtCore.QRect(745, 510, 225, 150))
        self.battery_pic.setText("")
        self.battery_pic.setScaledContents(True)
        self.battery_pic.setObjectName("battery_pic")
        self.picture.raise_()
        self.BR_speed_pic.raise_()
        self.BR_speed_label.raise_()
        self.FL_speed_pic.raise_()
        self.FL_speed_label.raise_()
        self.BL_speed_pic.raise_()
        self.BL_speed_label.raise_()
        self.BR_break_label.raise_()
        self.BR_break_pic.raise_()
        self.BR_steering_pic.raise_()
        self.BR_steering_label.raise_()
        self.BL_break_label.raise_()
        self.BL_break_pic.raise_()
        self.BL_steering_pic.raise_()
        self.BL_steering_label.raise_()
        self.FL_break_label.raise_()
        self.FL_break_pic.raise_()
        self.FL_steering_pic.raise_()
        self.FL_steering_label.raise_()
        self.FR_break_pic.raise_()
        self.FR_steering_pic.raise_()
        self.FR_speed_pic.raise_()
        self.FR_steering_label.raise_()
        self.Fr_break_label.raise_()
        self.FR_speed_label.raise_()
        self.FR_break_error_label.raise_()
        self.FR_break_error_pic.raise_()
        self.FR_steering_error_pic.raise_()
        self.FR_steering_error_label.raise_()
        self.FL_steering_error_pic.raise_()
        self.FL_steering_error_label.raise_()
        self.FL_break_error_label.raise_()
        self.FL_break_error_pic.raise_()
        self.BR_steering_error_pic.raise_()
        self.BR_steering_error_label.raise_()
        self.BR_break_error_label.raise_()
        self.BR_break_error_pic.raise_()
        self.BL_steering_error_label.raise_()
        self.BL_break_error_label.raise_()
        self.BL_steering_error_pic.raise_()
        self.BL_break_error_pic.raise_()
        self.grey_color.raise_()
        self.FL_FOV.raise_()
        self.FL_ultrasonic_label.raise_()
        self.FR_FOV.raise_()
        self.FR_ultrasonic_label.raise_()
        self.control_speed_label.raise_()
        self.control_speed_pic.raise_()
        self.control_steering_label.raise_()
        self.control_gear_label.raise_()
        self.control_break_pic.raise_()
        self.control_break_label.raise_()
        self.gear_pic.raise_()
        self.control_steering_pic.raise_()
        self.Reverse.raise_()
        self.Drive.raise_()
        self.Park.raise_()
        self.L_FOV.raise_()
        self.R_FOV.raise_()
        self.BR_FOV.raise_()
        self.BR_ultrasonic_label.raise_()
        self.BL_FOV.raise_()
        self.BL_ultrasonic_label.raise_()
        self.R_ultrasonic_label.raise_()
        self.L_ultrasonic_label.raise_()
        self.battery_pic.raise_()
        self.battery_temp_label.raise_()
        self.batter_percentage_label.raise_()
        self.battery_voltage_label.raise_()
        self.battery_current_label.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.BR_speed_label.setText(_translate("Dialog", "BR"))
        self.FL_speed_label.setText(_translate("Dialog", "FL"))
        self.BL_speed_label.setText(_translate("Dialog", "BL"))
        self.BR_break_label.setText(_translate("Dialog", "BR"))
        self.BR_steering_label.setText(_translate("Dialog", "BR"))
        self.BL_break_label.setText(_translate("Dialog", "BL"))
        self.BL_steering_label.setText(_translate("Dialog", "BL"))
        self.FL_break_label.setText(_translate("Dialog", "FL"))
        self.FL_steering_label.setText(_translate("Dialog", "FL"))
        self.FR_steering_label.setText(_translate("Dialog", "FR"))
        self.Fr_break_label.setText(_translate("Dialog", "FR"))
        self.FR_speed_label.setText(_translate("Dialog", "FR"))
        self.FR_break_error_label.setText(_translate("Dialog", "FR"))
        self.FR_steering_error_label.setText(_translate("Dialog", "FR"))
        self.FL_steering_error_label.setText(_translate("Dialog", "FL"))
        self.FL_break_error_label.setText(_translate("Dialog", "FL"))
        self.BR_steering_error_label.setText(_translate("Dialog", "BR"))
        self.BR_break_error_label.setText(_translate("Dialog", "BR"))
        self.BL_steering_error_label.setText(_translate("Dialog", "BL"))
        self.BL_break_error_label.setText(_translate("Dialog", "BL"))
        self.FR_ultrasonic_label.setText(_translate("Dialog", "FR"))
        self.FL_ultrasonic_label.setText(_translate("Dialog", "FL"))
        self.R_ultrasonic_label.setText(_translate("Dialog", "R"))
        self.L_ultrasonic_label.setText(_translate("Dialog", "L"))
        self.BR_ultrasonic_label.setText(_translate("Dialog", "BR"))
        self.BL_ultrasonic_label.setText(_translate("Dialog", "BL"))
        self.control_speed_label.setText(_translate("Dialog", "FR"))
        self.control_steering_label.setText(_translate("Dialog", "FR"))
        self.control_gear_label.setText(_translate("Dialog", "FR"))
        self.control_break_label.setText(_translate("Dialog", "FR"))
        self.Reverse.setText(_translate("Dialog", "R"))
        self.batter_percentage_label.setText(_translate("Dialog", "%"))
        self.battery_current_label.setText(_translate("Dialog", "A"))
        self.battery_temp_label.setText(_translate("Dialog", "C"))
        self.battery_voltage_label.setText(_translate("Dialog", "V"))
        self.Drive.setText(_translate("Dialog", "D"))
        self.Park.setText(_translate("Dialog", "P"))


